### ISSUE TITLE
Visible leaf armorstands

### ISSUE THREAD

**Issue by ItzPeto** [Masstrix/Eternal-Nature#12]
Hi,

this is my simple bug report. Armorstands are sometimes visible when using the falling leafs effect.

Heres a animated image where you can see this in action.
https://southcraft.cz/ItzPeto/files/_pn-ItzPeto-16-12-2020-22-43-20.gif

Edit: Okay i just found out that this happens when you get teleported to that location...

**Comment by Masstrix** [comment]
Thanks for the report, would you be able to be able to tell me the version and build number you are running. You can get this by using the command `/en version` and it will tell you both.

**Comment by Masstrix** [comment]
> Edit: Okay i just found out that this happens when you get teleported to that location...
Does this require someone to already be there when you teleport? So you teleport to a player and then you'll see the armour stands. Or can it also happen when you just teleport to any location even ones where there are no players nearby?

**Comment by ItzPeto** [comment]
Im running v2.1.1 build 987
And yes this only happens when teleporting to a player. Another thing i just discovered is that when a player dies the temperature completely glitches out and starts to go to -0.1° and still has the sunny icon (normally on theres 14° at spawn) and also the damage threshold gets glitched out and starts giving damage even when we have the dmg threshold at -15° and 45°

https://southcraft.cz/ItzPeto/files/unknown.png

**Comment by Masstrix** [comment]
OK yep, if you can create another issue with a way to replicate the temperature issue that would be great, just want to keep this issue about the leaves.

I think I might not what's happening with the leaves so I'll look into the matter a bit more and do some testing on my end to find exactly what causes it.

**Comment by Masstrix** [comment]
**UPDATE**
Armour stands that that are sent work as expected for the first player who joined the server, but anyone following that don't seem to get send all the metadata. If a player joins an empty server, they will see it fine. The next player who joins will be able to see the armour stand and it's also slightly offset from where it actually should be.

**Comment by Masstrix** [comment]
Bug has been solved when updating to 1.17.
