### ISSUE TITLE
The new placeholder are not correctly showed in wiki

### ISSUE THREAD

**Issue by Caishangqi** [Masstrix/Eternal-Nature#16]
When I try to use the newly updated placeholder in action bar, it not work.
Only the old one in eCloud works.

Then I try to use %eternalnature_temperature_color%, it works.
Seem like a typo :0

**Comment by Masstrix** [comment]
Fixed typo in wiki. This was a mistake on my side forgetting to add the identifier at the start of them. For version 2.1.1 the identifier is still `eternalnature` but future versions will use the identifier `nature` to slightly shorten the placeholders.
