### ISSUE TITLE
bugged kelp

### ISSUE THREAD

**Issue by divios** [Masstrix/Eternal-Nature#5]
Hi!

I just notice that sometimes the leafs (kelp) gets bugged and just keep there in the air. This can going to an extreme where there are infinite ammount of leafs and the chunks get pretty bugged. Deleting the armor stand doesn't seem to work, how could i fix this?

**Comment by Masstrix** [comment]
Thanks for the report. I've fixed this in my latest build and will be fixed in the next full release for version 2.1. The new version uses NMS to spawn the armour stands now so they won't stay.
